# Generated by Django 4.1.4 on 2022-12-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="styles",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="styles",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.TextField(),
        ),
    ]
