# Generated by Django 4.1.4 on 2023-01-01 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_logo_styles_alter_menuitem_styles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menugroup",
            name="styles",
            field=models.TextField(
                default="display: flex; align-items: center; justify-content: space-between; background-color: #333; color: #fff; font-size: 18px; font-weight: bold;"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="logo",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_logo",
                to="mainapp.menugroup",
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="styles",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="mainapp.menugroup",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="styles",
            field=models.TextField(),
        ),
    ]
