# Generated by Django 4.1.4 on 2023-01-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_menugroup_styles_alter_logo_menu_alter_logo_styles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="styles",
        ),
        migrations.AddField(
            model_name="menugroup",
            name="html",
            field=models.TextField(default="<div></div>"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menugroup",
            name="logo",
            field=models.ImageField(default="logos/logo.png", upload_to="logos"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="mainapp.menugroup",
            ),
        ),
        migrations.DeleteModel(
            name="Logo",
        ),
    ]
