# Generated by Django 4.1.4 on 2023-01-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainapp",
            "0004_remove_menuitem_styles_menugroup_html_menugroup_logo_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
