# Generated by Django 4.1.4 on 2023-01-04 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_delete_menuitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menugroup",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="mainapp.menugroup",
                    ),
                ),
            ],
        ),
    ]
