# Generated by Django 4.1.4 on 2023-01-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_remove_menugroup_logo_alter_menugroup_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="dropdown_links",
            field=models.TextField(default="home"),
            preserve_default=False,
        ),
    ]
