# Generated by Django 4.1.4 on 2023-01-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_menuitem_dropdown_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="dropdown_links",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.menuitem",
            ),
        ),
    ]
