# Generated by Django 4.1.4 on 2023-01-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_alter_menuitem_dropdown_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="dropdown",
            field=models.BooleanField(default=False),
        ),
    ]
