# Generated by Django 4.1.4 on 2023-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0014_remove_menuitem_dropdown_links_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="dropdown_links",
            field=models.ManyToManyField(to="mainapp.menuitem"),
        ),
    ]
